# Generated by Django 3.2.16 on 2023-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.BooleanField(default=False)),
                ('pause_inform_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Start/Stop',
            },
        ),
    ]
