# Generated by Django 3.2.16 on 2023-10-20 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231020_0252'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnnecessaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_link', models.CharField(max_length=500)),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inform', verbose_name='länk')),
            ],
        ),
    ]
