# Generated by Django 3.2.16 on 2023-10-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_unnecessaryfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unnecessaryfile',
            options={'ordering': ['-id']},
        ),
    ]
