# Generated by Django 3.2.16 on 2023-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230325_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeipadress',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
