# Generated by Django 3.2.16 on 2023-03-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_rangeipadress_date_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rangeipadress',
            unique_together={('first_part_ipaddress', 'start', 'end')},
        ),
    ]
