# Generated by Django 3.2.16 on 2026-02-08 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_rangeipaddress_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeipaddress',
            name='current_minute',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rangeipaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rangeipaddress',
            name='minute_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rangeipaddress',
            name='month_requests',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rangeipaddress',
            name='month_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rangeipaddress',
            name='rate_limit_per_minute',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many times per minute can a client send requests?', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rate limit per minute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rangeipaddress',
            name='rate_limit_per_month',
            field=models.PositiveBigIntegerField(default=1, help_text='How many times per month can a client send requests?', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rate limit per month'),
            preserve_default=False,
        ),
    ]
