# Generated by Django 3.2.16 on 2026-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_unknownipratelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeipaddress',
            name='can_see_text',
            field=models.BooleanField(default=False, help_text='Can this IP range see the full text of files?'),
        ),
    ]
