# Generated by Django 3.2.16 on 2026-04-21 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rangeipaddress_can_see_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('owner', models.CharField(blank=True, max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveSmallIntegerField(help_text='How many requests per minute?', validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_limit_per_month', models.PositiveBigIntegerField(help_text='How many requests per month?', validators=[django.core.validators.MinValueValidator(1)])),
                ('minute_requests', models.PositiveIntegerField(default=0)),
                ('current_minute', models.DateTimeField(blank=True, null=True)),
                ('month_requests', models.PositiveBigIntegerField(default=0)),
                ('month_started', models.DateTimeField(blank=True, null=True)),
                ('can_see_text', models.BooleanField(default=False, help_text='Can this API key see the full text of files?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
    ]
