# Generated by Django 3.2.16 on 2023-11-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20231116_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesanalytics',
            name='avg_engagement_time',
            field=models.IntegerField(default=0),
        ),
    ]
