# Generated by Django 3.2.16 on 2023-03-23 08:27

import django.core.validators
from django.db import migrations, models
import main.services


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230318_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetail',
            name='file',
            field=models.FileField(max_length=500, upload_to=main.services.file_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
