# Generated by Django 3.2.16 on 2023-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_filedetail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='searchdetail',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchdetail',
            name='text',
            field=models.CharField(max_length=600),
        ),
    ]
