# Generated by Django 3.2.16 on 2023-03-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_searchdetail_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='pdf_counts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
