# Generated by Django 3.2.16 on 2023-03-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_inform_pdf_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inform',
            old_name='pdf_counts',
            new_name='pdfs_count',
        ),
    ]
