# Generated by Django 3.2.16 on 2023-04-17 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230408_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('ble', 'Blekinge'), ('dal', 'Dalarna'), ('got', 'Gotland'), ('gav', 'Gävleborg'), ('hal', 'Halland'), ('jam', 'Jämtland'), ('jon', 'Jönköping'), ('kal', 'Kalmar'), ('kro', 'Kronoberg'), ('nor', 'Norrbotten'), ('ska', 'Skåne'), ('sto', 'Stockholm'), ('sod', 'Södermanland'), ('upp', 'Uppsala'), ('var', 'Värmland'), ('vab', 'Västerbotten'), ('van', 'Västernorrland'), ('vam', 'Västmanland'), ('vag', 'Västra Götaland'), ('ore', 'Örebro'), ('ost', 'Östergötland')], max_length=3, verbose_name='Län')),
                ('zip_file', models.FileField(upload_to='zip_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('pdfs_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('is_completed', models.BooleanField(default=False, verbose_name='är klart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='filedetail',
            name='zip_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.zipfileupload', verbose_name='Zip File'),
        ),
    ]
