# Generated by Django 3.2.16 on 2023-04-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230417_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipfileupload',
            name='country',
        ),
    ]
