# Generated by Django 3.2.16 on 2023-07-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230726_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='first_page_text',
            field=models.TextField(blank=True),
        ),
    ]
