# Generated by Django 3.2.16 on 2023-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_filedetail_first_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='join_text',
            field=models.TextField(blank=True),
        ),
    ]
