# Generated by Django 3.2.16 on 2023-09-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_filedetail_join_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedetail',
            name='join_text',
        ),
    ]
