# Generated by Django 3.2.16 on 2023-10-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_filedetail_join_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnnecessaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_link', models.CharField(max_length=500)),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inform')),
            ],
        ),
    ]
