# Generated by Django 3.2.16 on 2023-10-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231020_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='last_pdf',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
