# Generated by Django 3.2.16 on 2023-10-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_inform_last_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
