# Generated by Django 3.2.16 on 2026-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_filedetail_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='mode',
            field=models.CharField(choices=[('k', 'Kommun'), ('r', 'Region')], default='k', max_length=10),
        ),
    ]
