# Generated by Django 3.2.16 on 2026-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20260205_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetail',
            name='organ',
            field=models.CharField(choices=[('s', 'kommunstyrelsen'), ('f', 'kommunfullmäktige'), ('halso', 'Hälso- och sjukvårdsnämnden'), ('kollek', 'Kollektivtrafiknämnden'), ('regla', 'Regionala utvecklingsnämnden'), ('RS', 'Regionstyrelsen'), ('RF', 'Regionfullmäktige')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inform',
            name='organ',
            field=models.CharField(blank=True, choices=[('s', 'kommunstyrelsen'), ('f', 'kommunfullmäktige'), ('halso', 'Hälso- och sjukvårdsnämnden'), ('kollek', 'Kollektivtrafiknämnden'), ('regla', 'Regionala utvecklingsnämnden'), ('RS', 'Regionstyrelsen'), ('RF', 'Regionfullmäktige')], max_length=10, null=True),
        ),
    ]
