# Generated by Django 3.2.16 on 2026-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20260205_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetail',
            name='organ',
            field=models.CharField(choices=[('s', 'kommunstyrelsen'), ('f', 'kommunfullmäktige'), ('halso', 'Hälso- och sjukvårdsnämnden'), ('kollek', 'Kollektivtrafiknämnden'), ('regla', 'Regionala utvecklingsnämnden'), ('rs', 'Regionstyrelsen'), ('rf', 'Regionfullmäktige'), ('social', 'Social'), ('funkt', 'Funktionsstöd'), ('forsk', 'Förskola'), ('utbild', 'Utbildning'), ('garbet', 'Gymnasie / Arbetsmarknad'), ('arbet', 'Arbetsmarknad'), ('stadb', 'Stadsbyggnad / byggnadsnämnd'), ('miljh', 'Miljö & Hälsa'), ('aldre', 'Äldre'), ('kulfri', 'Kultur & fritid'), ('endas', 'Endas'), ('FRITID', 'fritid'), ('tekser', 'Tekniska / service'), ('trafik', 'Trafik'), ('exploat', 'Exploatering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inform',
            name='organ',
            field=models.CharField(blank=True, choices=[('s', 'kommunstyrelsen'), ('f', 'kommunfullmäktige'), ('halso', 'Hälso- och sjukvårdsnämnden'), ('kollek', 'Kollektivtrafiknämnden'), ('regla', 'Regionala utvecklingsnämnden'), ('rs', 'Regionstyrelsen'), ('rf', 'Regionfullmäktige'), ('social', 'Social'), ('funkt', 'Funktionsstöd'), ('forsk', 'Förskola'), ('utbild', 'Utbildning'), ('garbet', 'Gymnasie / Arbetsmarknad'), ('arbet', 'Arbetsmarknad'), ('stadb', 'Stadsbyggnad / byggnadsnämnd'), ('miljh', 'Miljö & Hälsa'), ('aldre', 'Äldre'), ('kulfri', 'Kultur & fritid'), ('endas', 'Endas'), ('FRITID', 'fritid'), ('tekser', 'Tekniska / service'), ('trafik', 'Trafik'), ('exploat', 'Exploatering')], max_length=10, null=True),
        ),
    ]
