# Generated by Django 3.2.16 on 2026-02-26 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20260216_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedetail',
            name='from_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filedetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
