# Generated by Django 3.2.16 on 2026-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20260226_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfileupload',
            name='errors_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='zipfileupload',
            name='skipped_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
